import sys
sys.path.insert(0, r"d:\woodworking_ai")
sys.stdout.reconfigure(encoding='utf-8')
import os
import pymupdf
import re

def is_valid_title(title):
    if not title or len(title.strip()) < 3:
        return False
    t_lower = title.lower().strip()
    bad_keywords = [
        "www.", "http", ".com", ".net", ".org", "construct101",
        "untitled", "document", "microsoft", "word", "pdf", "page",
        "legal", "disclaimer", "copyright", "free pdf", "generated by"
    ]
    if any(bad in t_lower for bad in bad_keywords):
        return False
    return True

def extract_real_project_title(pdf_path):
    doc = pymupdf.open(pdf_path)
    
    # 1. Check Page 1 and Page 2 Text Lines for Prominent Title
    for page_idx in range(min(2, len(doc))):
        raw_text = doc[page_idx].get_text("text") or ""
        lines = [l.strip() for l in raw_text.split("\n") if l.strip()]
        for l in lines:
            clean_l = re.sub(r'^ArtisanBlueprint\s*\|\s*', '', l, flags=re.I).strip()
            clean_l = re.sub(r'[\–\-]\s*(Overview|Material List|Cutting List|Shopping List|Free PDF).*', '', clean_l, flags=re.I).strip()
            clean_l = re.sub(r'Visit\s+www\.Construct101\.com.*', '', clean_l, flags=re.I).strip()
            clean_l = re.sub(r'www\.Construct101\.com', '', clean_l, flags=re.I).strip()
            
            if is_valid_title(clean_l):
                if any(kw in clean_l.lower() for kw in ["plans", "shed", "barn", "coop", "table", "bench", "door", "window", "greenhouse", "desk", "frame", "pergola", "chair"]):
                    return clean_l
                elif page_idx == 0 and 5 <= len(clean_l) <= 45 and not clean_l.endswith("."):
                    return clean_l

    # 2. Check PDF Metadata Title (only if valid and not a domain name)
    if doc.metadata and doc.metadata.get("title"):
        meta_t = doc.metadata.get("title", "").strip()
        if is_valid_title(meta_t):
            return meta_t

    # 3. Fallback to PDF Filename
    filename = os.path.basename(pdf_path)
    base_name = os.path.splitext(filename)[0]
    clean_filename = base_name.replace("-", " ").replace("_", " ").title()
    clean_filename = re.sub(r'\bPdf\b', '', clean_filename, flags=re.I).strip()
    return clean_filename

test_pdfs = [
    r"D:\ETSY\10x10 Barn Shed Plans.pdf",
    r"D:\ETSY\DIY Barn Style Greenhouse.pdf"
]

for pdf in test_pdfs:
    if os.path.exists(pdf):
        title = extract_real_project_title(pdf)
        print(f"File: {os.path.basename(pdf)} ---> Title: '{title}'")
