import sys
sys.path.insert(0, r"d:\woodworking_ai")
sys.stdout.reconfigure(encoding='utf-8')
import os
import pymupdf
import re

def extract_real_project_title(pdf_path):
    doc = pymupdf.open(pdf_path)
    
    # Strategy 1: Check PDF Metadata Title
    meta_title = doc.metadata.get("title", "") if doc.metadata else ""
    if meta_title and len(meta_title.strip()) > 3 and not any(kw in meta_title.lower() for kw in ["untitled", "document", "microsoft", "word", "pdf"]):
        return meta_title.strip()
        
    # Strategy 2: Check Page 1 and Page 2 Text Lines
    for page_idx in range(min(2, len(doc))):
        raw_text = doc[page_idx].get_text("text") or ""
        lines = [l.strip() for l in raw_text.split("\n") if l.strip()]
        
        for l in lines:
            # Clean common headers / watermarks
            clean_l = re.sub(r'^ArtisanBlueprint\s*\|\s*', '', l, flags=re.I).strip()
            clean_l = re.sub(r'[\–\-]\s*(Overview|Material List|Cutting List|Shopping List|Free PDF).*', '', clean_l, flags=re.I).strip()
            clean_l = re.sub(r'Visit\s+www\.Construct101\.com.*', '', clean_l, flags=re.I).strip()
            
            clean_l_lower = clean_l.lower()
            if not clean_l or any(kw in clean_l_lower for kw in ["legal", "disclaimer", "copyright", "construct101", "http", "page", "isbn", "generated by", "intermediate diy"]):
                continue
                
            if any(kw in clean_l_lower for kw in ["plans", "shed", "barn", "coop", "table", "bench", "door", "window", "greenhouse", "desk", "frame", "pergola", "chair"]):
                return clean_l
                
            # If line is short title-like text on Page 1 (e.g. 4x10 Shed Plans)
            if page_idx == 0 and 5 <= len(clean_l) <= 40 and not clean_l.endswith("."):
                return clean_l

    # Strategy 3: Fallback to PDF Filename
    filename = os.path.basename(pdf_path)
    base_name = os.path.splitext(filename)[0]
    clean_filename = base_name.replace("-", " ").replace("_", " ").title()
    clean_filename = re.sub(r'\bPdf\b', '', clean_filename, flags=re.I).strip()
    return clean_filename

test_pdfs = [
    r"D:\ETSY\10x10 Barn Shed Plans.pdf",
    r"D:\ETSY\12x12 Barn Shed Plans.pdf",
    r"D:\ETSY\DIY Barn Style Greenhouse.pdf"
]

for pdf in test_pdfs:
    if os.path.exists(pdf):
        title = extract_real_project_title(pdf)
        print(f"File: {os.path.basename(pdf)} ---> Title: '{title}'")
